# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruser', models.CharField(max_length=20)),
                ('uadress', models.CharField(max_length=50)),
                ('upc', models.CharField(max_length=50)),
                ('uphone', models.IntegerField(verbose_name=16)),
            ],
            options={
                'db_table': 'ttsx_recipients',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'ttsx_user',
            },
        ),
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=50)),
                ('out_time', models.DateTimeField()),
                ('ttsx_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserModel')),
            ],
            options={
                'db_table': 'user_ticket',
            },
        ),
        migrations.AddField(
            model_name='recmodel',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserModel'),
        ),
    ]
