# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=20)),
                ('gpic', models.CharField(max_length=200)),
                ('gprice', models.FloatField(default=0)),
                ('isDelete', models.IntegerField(default=1)),
                ('danwei', models.CharField(default='500g', max_length=20)),
                ('zhuangtai', models.IntegerField()),
                ('jieshao', models.CharField(max_length=200)),
                ('kucun', models.IntegerField(default=0)),
                ('guanjianzi', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('isDelete', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'goods_type',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TypeInfo'),
        ),
    ]
